# Tensors（张量）
## 这个文档介绍Tensorflow中各种创建tensor的方法

首先，我们import tensorflow，并reset计算图。


In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

/home/lxa/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.__version__

'1.6.0'

In [3]:
sess = tf.Session() # 创建一个会话

In [4]:
my_tensor = tf.zeros([1,20]) # 创建一个维度为4*20的全为零的张量。

In [5]:
sess.run(my_tensor) # 通过sess.run(...)来执行操作（计算图）

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [6]:
my_var = tf.Variable(tf.zeros([1,20])) # 创建一个维度为4*20的全为零的变量。（也是张量）
my_var1 = tf.get_variable('my_var1', initializer = tf.zeros([1,20])) # 另一种创建变量的方法（推荐）

In [7]:
sess.run(my_var) # 这样做会报错，原因是，variables需要先进行初始化之后才能够使用。

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _retval_Variable_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

In [8]:
sess.run(my_var.initializer) # 对my_var变量进行初始化
sess.run(my_var1.initializer)

In [9]:
sess.run(my_var)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [10]:
sess.run(my_var1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [11]:
# 创建变量总结：
#    1. 定义维度
#    2. 使用tf.Variable(...)或者tf.get_variable('var_name',...)
#    3. 使用sess.run(variable.initializer)进行初始化

row_dim = 3
col_dim = 2

zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
one_var = tf.get_variable('one_var',initializer = tf.ones([row_dim, col_dim]))

sess.run(zero_var.initializer)
sess.run(one_var.initializer)

print sess.run(zero_var)
print sess.run(one_var)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:

# 当有多个变量时，可以使用tf.global_variables_initializer()一次性都初始化

row_dim = 3
col_dim = 2

zero_var2 = tf.Variable(tf.zeros([row_dim, col_dim]))
one_var2 = tf.get_variable('one_var2',initializer = tf.ones([row_dim, col_dim]))

sess.run(tf.global_variables_initializer())

print sess.run(zero_var2)
print sess.run(one_var2)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
# 创建和其他张量维度一样的张量,可以使用tf.zeros_like(another_var)、tf.ones_like(another_var)

zero_sim = tf.get_variable('zero_sim', initializer = tf.zeros_like(zero_var))

sess.run(zero_sim.initializer)

print sess.run(zero_sim)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
# 给变量赋予各种初始值

fill_var1 = tf.get_variable('fill_var', initializer=tf.fill([row_dim, col_dim],-1))
sess.run(fill_var1.initializer)
print sess.run(fill_var1)

[[-1 -1]
 [-1 -1]
 [-1 -1]]


In [19]:
fill_var2 = tf.get_variable('fill_var2', initializer = tf.constant([[8,1],[2,3],[7,4]]))
sess.run(fill_var2.initializer)
print sess.run(fill_var2)

[[8 1]
 [2 3]
 [7 4]]


In [20]:
# 创建一个有序列信息的变量，可以使用tf.linspace(...)和tf.range(..)方法

line_var = tf.get_variable('line_var', initializer = tf.linspace(start=0.0, stop=1.0, num=4))
rang_var = tf.get_variable('rang_var', initializer = tf.range(start=6, limit=15, delta=3))
sess.run(line_var.initializer)
sess.run(rang_var.initializer)
print sess.run(line_var)
print sess.run(rang_var)

[0.         0.33333334 0.6666667  1.        ]
[ 6  9 12]


In [21]:
# 创建包含随机数的tensor
rand_var1 = tf.get_variable('rand_var1', initializer = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0))
rand_var2 = tf.get_variable('rand_var2', initializer = tf.random_uniform([row_dim, col_dim],minval=0, maxval=4))
sess.run(rand_var1.initializer)
sess.run(rand_var2.initializer)
print sess.run(rand_var1)
print sess.run(rand_var2)

# tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0) 随机数来源于正态分布的x值，mean指定均值，stddev指定标准差
# tf.random_uniform([row_dim, col_dim],minval=0, maxval=4)) 随机数来源于[0, 4)


[[-0.34947377  0.92263293]
 [-0.43971977 -1.67415   ]
 [ 0.79268014  0.8204375 ]]
[[0.02130365 3.2336555 ]
 [0.8333416  1.627029  ]
 [0.44216108 0.7178774 ]]


In [31]:
# 通过tensorboard来可视化变量

ops.reset_default_graph() # 重制graph

sess = tf.Session() # 开启一个会话

# 定义变量
rand_var1 = tf.get_variable('rand_var1', initializer = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0))
rand_var2 = tf.get_variable('rand_var2', initializer = tf.random_uniform([row_dim, col_dim],minval=0, maxval=4))

merged = tf.summary.merge_all() # 将所有的tensor添加到tensorboard
writer = tf.summary.FileWriter('/tmp/tf/variable_logs', graph=sess.graph) # 初始化一个graph writer，用于保存计算图。

In [32]:
sess.run(tf.global_variables_initializer())
sess.run(rand_var1)
sess.run(rand_var2)

array([[0.7985754 , 0.61133623],
       [0.04871941, 0.678041  ],
       [0.40822315, 1.2143188 ]], dtype=float32)