# 矩阵及其操作
这里讲述各种创建矩阵的方法以及其在tensorflow中的使用。

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

/home/lxa/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
sess = tf.Session()

## 创建矩阵

In [3]:
# 定义单位阵（Identity Matrix）

identity_matrix = tf.diag([1.0,1.0,1.0])
sess.run(identity_matrix)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [8]:
# 定义2*3的随机矩阵

random_matrix = tf.truncated_normal([2,3]) # [-1,1]
print sess.run(random_matrix)

C = tf.random_uniform([3,2]) # [0,1]
print(sess.run(C))

[[ 0.49994045 -1.4941657  -0.41872942]
 [ 0.8820672  -0.41305533  0.69380933]]
[[0.9806644  0.02443719]
 [0.8431717  0.7008257 ]
 [0.5200267  0.9575081 ]]


In [11]:
# 定义一个2*3的每个值都是5.0的矩阵

B = tf.fill([3,2], 5.0)
print(sess.run(B))

[[5. 5.]
 [5. 5.]
 [5. 5.]]


In [12]:
# 将numpy矩阵转换为tensor

matrix_np = np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]])
matrix_tf = tf.convert_to_tensor(matrix_np)
sess.run(matrix_tf)

array([[ 1.,  2.,  3.],
       [-3., -7., -1.],
       [ 0.,  5., -2.]])

## 矩阵操作

In [13]:
# 矩阵加法、减法

print sess.run(C+B)
print sess.run(C-B)

[[5.8030887 5.2771344]
 [5.9749775 5.7770815]
 [5.7584696 5.217642 ]]
[[-4.4853106 -4.7583013]
 [-4.86674   -4.99822  ]
 [-4.199946  -4.371274 ]]


In [ ]:
# 